### ISSUE TITLE
Poročilo na binderju se ne prevede

### ISSUE THREAD

**Issue by MatejRojec** [MatejRojec/APPR-2020-21#2]
Poročilo se mi na Windowsih in Mac-u prevede, na binderju pa mi vrže napako, bi prosil, če bi pogledali, kaj je narobe.

**Comment by katarinabrilej** [comment]
Meni se poročilo trenutno ne prevede tudi na Mac-u. Sklepam, da je težava v uvozu, saj se mi tudi ta ne prevede. Težava je v tabeli `h_mean`. Problem je, ko s funkcijo `rbind` združiš tabele, vendar pa stolpec `HM` ni povsod istega tipa. Kjer je tabela uvožena s funkcijo `hmean1`, `HM` ni številka, če pa je uvožena s `hmean2`, je številka. To lahko rešiš tako, da na koncu funkcije `hmean1` dodaš vrstico `h_mean$HM <- as.numeric(as.character(h_mean$HM))`. Potem na združeni tabeli ni več potrebno uporabiti `parse_number`. 
```
hmean1 <- function(tabela,leto){
  h_mean <- tabela %>% 
    select(occ_title,h_mean) %>% 
    rename(HM=h_mean) %>% 
    mutate(leto=c(leto)) %>% 
    .[c(1,3,2)] %>%
    drop_na(HM)
  h_mean$HM <- as.numeric(as.character(h_mean$HM))
  return(h_mean)
}
```
Enak problem je tudi pri tabeli `h_med`, v funkcijo `hmedian 1` dodaš 
```
h_med$HME <- as.numeric(as.character(h_med$HME))
```

Tudi v funkcijo `hmean3` lahko dodaš vrstico `hmean_state$HM <- as.numeric(as.character(hmean_state$HM))`, da bodo to številke. 

Problem je še pri tabli `h_med_s`, tam dodaš v funkcijo `hmedian3` naslednji dve vrstici
```
h_median_state$HM <- as.numeric(as.character(h_median_state$HM))
h_median_state$HME <- as.numeric(as.character(h_median_state$HME))
```

Tako se mi zdi, da bi se mogel prevesti celoten uvoz.

**Comment by katarinabrilej** [comment]
Poleg tega je bolje, če premakneš vse knjižnice v datoteko `libraries.r` v mapi `lib`, da jih nimaš nekaj na začetka uvoza in nekaj na začetku vizualizacije (ki se potem ponavljajo in se dvojno kličejo, ko poženeš poročilo).

**Comment by MatejRojec** [comment]
Sem popravil in sedaj se prevede poročilo kot se bi moralo, hvala za pomoč.
