### ISSUE TITLE
Organizacija podatkov

### ISSUE THREAD

**Issue by jaanos** [MatejRojec/APPR-2020-21#4]
Vidim, da pri uvozu in vizualizaciji narediš veliko tabel - pogosto z enim samim podatkom in posamezno podmnožico vrstic. Kot je bilo namignjeno v #3, ti tega ni potrebno početi - raje poskrbi, da imaš podatke v nekaj "velikih" razpredelnicah v obliki *tidy data*, iz njih pa sproti filtriraš in izbiraš podatke za vizualizacijo in analizo.

Že pri uvozu se lahko izogneš ustvarjanju velikega števila razpredelnic. Pri tem svetujem, da namesto vgrajene funkcije `read.csv2` (s piko) uporabiš funkcijo `read_csv2` (s podčrtajem) iz knjižnice `readr` - ta je veliko bolj robustna, z njeno uporabo pa se tudi izogneš težavam iz #2. Tako bi celoten uvoz nacionalnih podatkov lahko naredil tako:
```R
library(stringr) # za str_to_sentence in str_replace

dec <- grp <- c()
dec[6:9] <- grp[10:19] <- "."
dec[10:19] <- grp[6:9] <- ","

nat <- lapply(6:18, function(leto)
  sprintf("podatki/N_%02d.csv", leto) %>%
    read_delim(delim=";", na=c("", "#", "*", "**", "***"), trim_ws=TRUE,
               locale=locale(encoding="UTF-8", decimal_mark=dec[leto],
                             grouping_mark=grp[leto]),
               col_names=FALSE, skip=1) %>% # imena stolpcev se razlikujejo, zato bomo podali svoja
    transmute(leto=2000+leto, occ_code=factor(X1),
              occ_title=str_to_sentence(X2) %>% str_replace("[*]", ""),
              emp=X4, h_mean=X6, a_mean=X7, h_median=X11, a_median=X16)) %>%
  bind_rows(read_csv2("podatki/N_19.csv", na=c("", "#", "*", "**", "***")) %>%
              transmute(leto=2019, occ_code, occ_title, emp=tot_emp,
                        h_mean, a_mean, h_median, a_median)) %>%
  unique() # nekatere vrstice se ponovijo, tako da se teh znebimo
```
Taka razpredelnica še ni v obliki *tidy data*, tako da jo bo potrebno razbiti na več razpredelnic. Najprej opazimo, da je ime poklica odvisno od kode poklica, tako da bo treba to ločiti. Imena poklicev sicer niso povsod zapisana na isti način, tako da bo koda boljši identifikator - nekaj poenotenja se naredi že v zgornjem uvozu (velikost črk, odstranjevanje zvezdic), a to ni dovolj, tako da lahko vzamemo za vsako kodo eno od imen (lahko kar prvega):
```R
kode <- nat %>% select(occ_code, occ_title) %>%
  group_by(occ_code) %>% slice_head(n=1)
```
Podoben pristop (`group_by` in `slice*`) lahko uporabiš pri vizualizaciji, da ne bo potrebno delati rezin za vsako leto posebej.

Nadalje je v razpredelnici `nat` še 5 stolpcev, od katerih imamo dva para s povprečjem in mediano. Preostali stolpec lahko tako izločimo v svojo razpredelnico:
```R
t_e <- nat %>% select(occ_code, leto, emp)
```

Za podatka `h` in `a` imamo torej povprečja in mediane - ker so za vsak podatek na isti lestvici, bi jih bilo smiselno spraviti v isti stolpec. Ker so imena stolpcev že v ustrezni obliki, lahko narediš nekaj takega:
```R
nat.ha <- nat %>% select(occ_code, leto, h_mean, a_mean, h_median, a_median) %>%
  pivot_longer(c(-occ_code, -leto), names_to="podatek_sredina", values_to="vrednost") %>%
  separate(podatek_sredina, c("podatek", "sredina"), sep="_") %>%
  pivot_wider(names_from=podatek, values_from=vrednost)
```

Na podoben način se lahko lotiš tudi podatkov po zveznih državah. Ker se tukaj imena uvoženih stolpcev ujemajo, lahko narediš poenoten uvoz:
```R
st <- lapply(6:18, function(leto)
  sprintf("podatki/S_%02d.csv", leto) %>%
    read_delim(delim=";", na=c("", "#", "*", "**", "***"),
               locale=locale(encoding="UTF-8", decimal_mark=dec[leto],
                             grouping_mark=grp[leto])) %>%
    transmute(leto=2000+leto, state=STATE, occ_code=OCC_CODE, emp=TOT_EMP,
              h_mean=H_MEAN, a_mean=A_MEAN, h_median=H_MEDIAN, a_median=A_MEDIAN)) %>%
  bind_rows(read_csv2("podatki/S_19.csv", na=c("", "#", "*", "**", "***")) %>%
              transmute(leto=2019, state=area_title, occ_code, emp=tot_emp,
                        h_mean, a_mean, h_median, a_median)) %>% unique()
```
Naj opozorim, da imena poklicev že imaš, tako da bo tukaj zadostovalo, da uvoziš kode poklicev.

**Comment by MatejRojec** [comment]
Se mi zdi da uvoz ne deluje čisto pravilno od leta 2006 do 2009,  ker npr. za leto 2009, če pogledamo kolikšno je ura postavka kriurgov piše da je 10566. Kako bi pa v tem primeru to popravil? Zdi se mi, da je problem v tem, da v csv datoteki od 2010 do 2018 so ločene večja števila s piko, medtem ko pa v letih od 2006 do 2009 te pike ni. Torej namesto, da bi bilo 105,66 je kar 10566, enak problem se pojavi za veliko drugih poklicev.

**Comment by MatejRojec** [comment]
Potem imam pa še eno vprašanje glede tabele nat.ha, ali potem naredeim še 2 tabeli posebaj v kateri je v eni sam a, v eni pa samo h, ali je tako kot je sedaj vredu?

**Comment by jaanos** [comment]
Res je, oblika števil je drugačna v podatkih do 2009. Ker `read_csv2` ne dovoli spreminjanja ločila decimalk in tisočic, bo potrebno uporabiti `read_delim`, pri tem pa ustrezna ločila podati z `locale` - sem kar uredil primera v prvotni objavi. Prav tako se pri nacionalnih podatkih do 2009 pred števili pojavljajo še presledki, tako da je potrebno s `trim_ws=TRUE` poskrbeti, da se ignorirajo - potem se števila ustrezno razumejo.

Razpredelnice `nat.ha` ni potrebno ločiti na dve - kjer so podatki odvisni od istih dimenzij, so lahko v skupni razpredelnici. V tvojem primeru imaš torej v `kode` eno dimenzijo (koda), v `t_e` dve dimenziji (koda, leto), v `nat.ha` pa tri dimenzije (koda, leto, tip sredine). Pri podatkih za zvezne države pa boš seveda izpeljal razpredelnici, ustrezni zadnjima dvema, kjer kot dodatna dimenzija nastopa še zvezna država.

**Comment by jaanos** [comment]
Sem zdaj popravil uvoz tako, da dobiš zraven še podatke za 2019. Pri podatkih po zvezni državi je manjkal ravno ta podatek, tako da se ta sedaj uvozi.

**Comment by MatejRojec** [comment]
Sedaj mi na mojem računalniku uvoz deluje in se mi tudi poročilo prevede, edino sedaj se mi je ustvaril problem pri shiny-ju , pri risanju histograma mi, vrne error: 
```R
Error in seq.default: 'from' must be a finite number
```
ne vem točno kar je narobe, ker mi je prej to delalo vredu. 
Poleg tega se mi pa poročilo na binder-ju spet ne prevede, samo tokrat ne vem točno v čem je napaka.

**Comment by jaanos** [comment]
Težava se pojavi, ker imaš med podatki vrednosti `NA` - verjetno si želel `x.2` črpati iz `x`.

Sicer pa svetujem, da tudi histogram rišeš z `ggplot`, npr.
```R
  output$distPlot <- renderPlot({
    ggplot(nat.ha %>% filter(sredina == "mean", h > 100), aes(x=h)) +
      geom_histogram(bins=input$bini, fill="yellow", color="black") +
      xlab("Pojavljenost plače") + ylab("Frekvenca") +
      ggtitle("Histogram povprečnih plač")
  })
```

Nisem sicer prepričan, kaj je mišljeno s terminom *pojavljenost* plače - kaj pravzaprav meri podatek `h` (ta je prikazan na osi x)? Termin *pojavnost* se včasih uporablja za absolutno frekvenco (tj., število pojavitev - kar prikazuješ na osi y).

Drugače sem pa poskusil zagnati na Binderju, pa deluje (z izjemo histograma). Sicer bi ti svetoval, da na grafih namesto šifer prikažeš imena poklicev (pri prikazu uporabi `inner_join`, da pridružiš razpredelnico `kode`).

**Comment by MatejRojec** [comment]
Sedaj sem zamenjal kode z imeni poklicev in popravil tudi histogram (osi sem namreč napačno poimenoval) in se mi zdi da vse deluje. Hvala za pomoč.
