### ISSUE TITLE
Zaključek projekta

### ISSUE THREAD

**Issue by MatejRojec** [MatejRojec/APPR-2020-21#6]
Pozdravljeni,
mislim, da sem s svojim projektom končal in bi prosil še za zadnji pregled pred oddajo.

**Comment by katarinabrilej** [comment]
Meni se poročilo v Binderju ne prevede, ne vem pa kaj je razlog, saj ni nobenega errorja. Prav tako se ne prevede, če v Binderju poženem Rstudio in od tam poročilo. Če si projekt naložim na računalnik pa se mi prevede. 

V grafu Porazdelitev plač boljše plačanih poklicev je lepše, če so poklici v slovenščini, namesto v angleščini. 

Enako velja za naslednji graf, legenda naj bo v slovenščini. Tudi naslov legende naj bo z veliko začetnico, da bo usklajeno. Podobno za preostale grafe. 

Pri zemljevidu kjer so predstavljene povprečne plače v ZDA ni jasna enota v kateri so plače. Nasploh naj bo na vseh grafih jasno označeno v kateri enoti so številke, brez da je potrebno to informacijo iskati v tekstu. 

Torej naslovi legend naj bodo vsi z veliko začetnico, imena pa v slovenščini.

**Comment by MatejRojec** [comment]
Zdi se mi da sem popravil navedeno, če sem pa še kaj spregledal pa prosim sporočite.

**Comment by jaanos** [comment]
Glede na to, da poročilo deluje, bom dodal povezavo do projekta na repozitorij za zagovore, tako da se lahko z @alenFMF domeniš za termin zagovora. Če boš do takrat še kaj spreminjal, javi, da posodobim povezavo.

Imam samo še eno pripombo: *Število binov* bi lahko lepše zapisal kot *Število skupin* (ali morda *košev* za dobesedni prevod).

Kar se tiče poganjanja na Binderju, tudi sam nimam ideje, kaj je narobe. Ko sem včeraj poskusil, je namreč delovalo, danes pa spet ne.

**Comment by MatejRojec** [comment]
Sem popravil zato bi prosil, da posodobite povezavo.

**Comment by jaanos** [comment]
V redu, sem posodobil.
